# Docker containers for the Django server, Redis, Celery, and MySQL database

services:

  django:

    container_name: transit_server

    build:
      context: ./backend

    volumes:
      - transit_server_data:/data
      - ./backend:/usr/src/backend

    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: $EMAIL_USE_TLS}
      EMAIL_USE_SSL: ${EMAIL_USE_SSL}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}

    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy

    ports:
      - 8000:8000

  redis:

    image: redis:alpine

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  celery: # Celery Worker Node

    build:
      context: ./server

    environment:
      DEBUG: 1
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DJANGO_SETTINGS_MODULE: backend.settings
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}

    command: celery -A backend worker -l info

    volumes:
      - ./backend:/usr/src/backend
      - server_data:/data

    depends_on:
      - django
      - mysql
      - redis

  celery-beat: # Celery Task Scheduler

    build:
      context: ./backend

    command: celery -A backend beat -l info

    volumes:
      - ./backend:/usr/src/backend
      - server_data:/data

    environment:
      DEBUG: 1
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DJANGO_SETTINGS_MODULE: backend.settings
      TRANSIT_DB_HOST: mysql
      TRANSIT_DB_PORT: 3306
      TRANSIT_DB_NAME: ${DB_NAME}
      TRANSIT_DB_PASSWORD: ${DB_PASSWORD}
      TRANSIT_DB_USER: ${DB_USER}

    depends_on:
      - django
      - mysql
      - redis

  mysql:

    container_name: transit_server_mysql_db
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ${DB_USER} --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 2s
      timeout: 5s
      retries: 20
    ports:
      - 127.0.0.1:3307:3306 # Localhost

volumes:

  server_data:
  db_data:
