# Generated by Django 5.0.6 on 2026-04-26 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_department_course_department_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturesection',
            old_name='department',
            new_name='department_code',
        ),
        migrations.RenameField(
            model_name='nonlecturesection',
            old_name='department',
            new_name='department_code',
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department_code',
            field=models.CharField(default='No department', max_length=100),
        ),
    ]
