# Generated by Django 5.0.6 on 2026-04-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_department_lecturesection_department_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturesection',
            old_name='number',
            new_name='course_number',
        ),
        migrations.RenameField(
            model_name='nonlecturesection',
            old_name='number',
            new_name='course_number',
        ),
    ]
